[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {workspace = true}
aes = {workspace = true}
cbc = {workspace = true}
env_logger = {workspace = true}

log = {workspace = true}
rand = {workspace = true}
rsa =  {workspace = true}

[dev-dependencies]
iai-callgrind = "0.11.1"

[[bench]]
name = "cipher_bench"
harness = false # using a custom benchmarker (iai)
